version: 2

sources:
  - name: dvdrental
    database: "{{ target.database }}"
    schema: "{{ 'RAW' if target.type == 'snowflake' else 'public' }}"

    tables:
      - name: customer
      - name: rental
      - name: payment
      - name: campaign_results
      - name: customer_segment
