select
cr.customer_id,
cr.campaign_id,
cr.campaign_name,
cs.country,
cr.start_date,
cr.end_date,
cs.primary_segment,
cs.customer_tier,
cr.customer_segment,
cs.fav_film_ctgry,
cs.recency_segment,
cs.is_champion,
cs.is_churn_watchlist,
cs.is_engagement_growth,
cs.is_narrow_explorer,
cs.is_upsell_core,
cs.is_upsell_scale,
cs.is_winback_growth,
cs.is_winback_reactivation,
cs.is_winback_vip,
cr.treatment_group,
cr.conversion_flag,
cr.campaign_revenue,
cs.category_engagement_tier,
offer_cost,
contact_cost,
offer_cost + contact_cost as total_campaign_cost
from {{ ref('stg_campaign_results') }} cr join {{ ref('stg_customer_segment') }} cs
	on cr.customer_id = cs.customer_id